=== ThuCommix/Concordia.Framework/Nightingale/Entity.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Entity" type="Entity" />

    <xs:complexType name="Entity">
        <xs:sequence>
            <xs:element name="Fields" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Field" type="Field" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="ListFields" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ListField" type="ListField" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="VirtualFields" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="VirtualField" type="VirtualField" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="VirtualListFields" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="VirtualListField" type="VirtualListField" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Interfaces" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Interface" type="Interface" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Namespaces" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Import" type="Import" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="Name" type="xs:string" use="required" />
        <xs:attribute name="Description" type="xs:string" use="optional" />
        <xs:attribute name="Table" type="xs:string" use="optional" />
        <xs:attribute name="Namespace" type="xs:string" use="required" />
    </xs:complexType>

	<xs:simpleType name="Cascade">
	  <xs:restriction base="xs:string">
	    <xs:enumeration value="None" />
	    <xs:enumeration value="Save" />
	    <xs:enumeration value="SaveDelete" />
	  </xs:restriction>
	</xs:simpleType>

    <xs:complexType name="Field">
        <xs:attribute name="Name" type="xs:string" use="required" />
        <xs:attribute name="Description" type="xs:string" use="optional" />
        <xs:attribute name="FieldType" type="xs:string" use="required" />
        <xs:attribute name="Mandatory" type="xs:boolean" use="optional" />
        <xs:attribute name="Cascade" type="Cascade" use="required" />
        <xs:attribute name="MaxLength" type="xs:integer" use="optional" />
        <xs:attribute name="Unique" type="xs:boolean" use="optional" />
		<xs:attribute name="DecimalPrecision" type="xs:integer" use="optional" />
		<xs:attribute name="DecimalScale" type="xs:integer" use="optional" />
		<xs:attribute name="DateOnly" type="xs:boolean" use="optional" />
        <xs:attribute name="EagerLoad" type="xs:boolean" use="optional" />
        <xs:attribute name="Enum" type="xs:boolean" use="optional" />
    </xs:complexType>

	<xs:complexType name="ListField">
        <xs:attribute name="Name" type="xs:string" use="required" />
        <xs:attribute name="Description" type="xs:string" use="optional" />
        <xs:attribute name="FieldType" type="xs:string" use="required" />
        <xs:attribute name="Cascade" type="Cascade" use="required" />
        <xs:attribute name="ReferenceField" type="xs:string" use="required" />
        <xs:attribute name="EagerLoad" type="xs:boolean" use="optional" />
	</xs:complexType>

	<xs:complexType name="VirtualField">
        <xs:attribute name="Name" type="xs:string" use="required" />
        <xs:attribute name="Description" type="xs:string" use="optional" />
        <xs:attribute name="FieldType" type="xs:string" use="required" />
        <xs:attribute name="Expression" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="VirtualListField">
        <xs:attribute name="Name" type="xs:string" use="required" />
        <xs:attribute name="FieldType" type="xs:string" use="required" />
        <xs:attribute name="Expression" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="Interface">
		<xs:attribute name="Name" type="xs:string" use="required" />
	</xs:complexType>

    <xs:complexType name="Import">
        <xs:attribute name="Name" type="xs:string" use="required" />
    </xs:complexType>
	
</xs:schema>

=== ThuCommix/Concordia.Framework/Samples/ConsoleApp1/Address.xml
<?xml version="1.0" encoding="utf-8" ?>
<Entity Name="Address" Namespace="ConsoleApp1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../../Concordia.Framework/Entity.xsd">
    <Fields>
        <Field Name="Person" FieldType="Person" Mandatory="true" Cascade="None" />
        <Field Name="IsValid" FieldType="bool" Mandatory="true" Cascade="None" />
        <Field Name="ValidFrom" FieldType="DateTime" Mandatory="true" DateOnly="true" Cascade="None" />
        <Field Name="ValidTo" FieldType="DateTime" Mandatory="false" DateOnly="false" Cascade="None" />
        <Field Name="Zip" FieldType="string" MaxLength="12" Mandatory="true" Cascade="None" />
        <Field Name="Town" FieldType="string" MaxLength="50" Mandatory="true" Cascade="None" />
        <Field Name="Street" FieldType="string" MaxLength="100" Mandatory="true" Cascade="None" />
        <Field Name="Type" FieldType="AddressType" Enum="true" Mandatory="true" Cascade="None" />
    </Fields>
</Entity>

=== ThuCommix/Concordia.Framework/Samples/ConsoleApp1/Person.xml
<?xml version="1.0" encoding="utf-8" ?>
<Entity Name="Person" Namespace="ConsoleApp1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../../ThuCommix.EntityFramework/Entity.xsd">
    <Fields>
        <Field Name="FirstName" FieldType="string" Mandatory="true" MaxLength="50" Cascade="None" />
        <Field Name="Name" FieldType="string" Mandatory="true" MaxLength="50" Cascade="None" />
        <Field Name="Age" FieldType="int" Mandatory="false" Cascade="None" />
        <Field Name="IsLegalAge" FieldType="bool" Mandatory="false" Cascade="None" />
    </Fields>
    <ListFields>
        <ListField Name="Addresses" FieldType="Address" ReferenceField="Person" Cascade="SaveDelete" />
    </ListFields>
    <VirtualFields>
        <VirtualField Name="FullName" FieldType="string" Expression="$&quot; {Name}, {FirstName}&quot;" />
    </VirtualFields>
    <VirtualListFields>
        <VirtualListField Name="ValidAddresses" FieldType="Address" Expression="Addresses.Where(x =&gt; x.IsValid).ToList()" />
    </VirtualListFields>
</Entity>
